### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by akshayaCap** [braindead/logmmse#1]
I am getting this error while executing the logmmse.py file.
Command: python logmmse.py input.wav output.wav

 UserWarning: Could not import alsa backend; most probably, you did not have alsa headers when building audiolab
  warnings.warn("Could not import alsa backend; most probably, "
Traceback (most recent call last):
  File "logmmse.py", line 109, in <module>
    output, saved_params = logmmse(signal, fs, args.initial_noise, args.window_size, args.noise_threshold, saved_params)
  File "logmmse.py", line 28, in logmmse
    x_old = np.zeros(len1)
TypeError: 'float' object cannot be interpreted as an index

Please let me know if there is any fix for this. Thank you.

**Comment by rajivpoddar** [comment]
Is this with Python 2 or 3? It's not yet ported to Python 3.

**Comment by akshayaCap** [comment]
Thanks for your prompt reply. It is with Python 2.

**Comment by rajivpoddar** [comment]
What's the sampling rate and duration of the audio file? Can you post the output of `soxi`.

**Comment by akshayaCap** [comment]
Output of soxi:

Input File     : 'CafeteriaMic.wav'
Channels       : 1
Sample Rate    : 48000
Precision      : 16-bit
Duration       : 00:00:24.00 = 1152000 samples ~ 1800 CDDA sectors
File Size      : 2.30M
Bit Rate       : 768k
Sample Encoding: 16-bit Signed Integer PCM

**Comment by rajivpoddar** [comment]
It's most probably the sampling rate which is causing the issue. I never tested with anything more than 16 kHz I think.

**Comment by akshayaCap** [comment]
I tried with 8 KHz and 16 KHz as well. Same error. Can you provide output of soxi. Or if you could tell the properties of the audio sample file you has used.
Thank you.

**Comment by rajivpoddar** [comment]
I actually don't have it. Worked on this a long time back. Try this one instead. https://github.com/braindead/mmse-port
